when:
  event: manual

priority: 9
skip_clone: true

labels:
  demo: c3

steps:
  - name: waiting-demo
    image: bash
    commands:
      - echo "C3 scheduler demo"
      - ech0 "长任务自动化管线执行中..."
      - sleep 1200
